# Generated by Django 5.2 on 2025-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('years_worked', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('ssn', models.CharField(max_length=20)),
                ('education', models.TextField(blank=True)),
                ('career', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
            ],
        ),
    ]
