# Generated by Django 5.2 on 2025-04-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2025-04-01', verbose_name='입사일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='resign_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
    ]
