# Generated by Django 5.2 on 2025-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_hire_date_employee_resign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(error_messages={'unique': '이미 존재하는 사번입니다.'}, max_length=20, unique=True),
        ),
    ]
