# Generated by Django 5.2 on 2025-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder',
            field=models.CharField(blank=True, max_length=50, verbose_name='예금주'),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='연봉'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='월급여'),
        ),
    ]
