# Generated by Django 5.2 on 2025-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_account_holder_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('재직', '재직'), ('퇴직', '퇴직'), ('휴직', '휴직')], default='재직', max_length=10, verbose_name='상태'),
        ),
    ]
