# Generated by Django 5.2 on 2025-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='휴직기간'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='휴직종류'),
        ),
    ]
