# Generated by Django 5.2 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employee_leave_period_employee_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank_base_date',
            field=models.DateField(blank=True, null=True, verbose_name='직급 기준일'),
        ),
    ]
