# Generated by Django 5.2 on 2025-04-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee_rank_base_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rank_base_date',
        ),
    ]
