# Generated by Django 5.2 on 2025-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_employee_rank_base_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank_base_date',
            field=models.DateField(blank=True, null=True, verbose_name='직급 기준일'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_worked',
            field=models.IntegerField(default=0, verbose_name='년차'),
        ),
    ]
