# Generated by Django 5.2 on 2025-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employee_rank_base_date_alter_employee_years_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rank_base_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_worked',
            field=models.IntegerField(),
        ),
    ]
