# Generated by Django 5.2 on 2025-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_employee_rank_base_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='직급 기준일'),
        ),
    ]
