# Generated by Django 5.2 on 2025-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_employee_position_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('정규직', '정규직'), ('계약직', '계약직'), ('아르바이트', '아르바이트')], default='정규직', max_length=20, verbose_name='고용형태'),
        ),
    ]
