# Generated by Django 5.2 on 2025-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employee_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('육아휴직', '육아휴직'), ('산재휴가', '산재휴가'), ('출산휴가', '출산휴가'), ('일반휴직', '일반휴직'), ('기타', '기타')], max_length=50, verbose_name='휴직종류'),
        ),
    ]
