# Generated by Django 5.2 on 2025-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_employee_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leave_period',
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='휴직 종료일'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='휴직 시작일'),
        ),
    ]
