# Generated by Django 5.2 on 2025-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_employee_leave_period_employee_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
    ]
