# Generated by Django 5.2 on 2025-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, help_text='jpg, jpeg, png만 업로드 가능합니다.', null=True, upload_to='employee_photos/', verbose_name='사진'),
        ),
    ]
