# Generated by Django 5.2 on 2025-05-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_employee_gender_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='annual_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='career',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='monthly_salary',
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('acquired_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_salary', models.IntegerField()),
                ('monthly_salary', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to='myapp.employee')),
            ],
        ),
    ]
