# Generated by Django 5.2 on 2025-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_employee_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinfo',
            name='account_holder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='annual_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='monthly_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
