# Generated by Django 5.2 on 2025-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_salaryinfo_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinfo',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
