# Generated by Django 5.2 on 2025-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_salaryinfo_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
