# Generated by Django 5.2 on 2025-05-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_employee_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
