# Generated by Django 5.2 on 2025-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_employee_age_employee_birth_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='나이'),
        ),
    ]
