# Generated by Django 5.2 on 2025-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
