# Generated by Django 5.2 on 2025-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_employee_birth_number_alter_employee_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(max_length=20),
        ),
    ]
