# Generated by Django 5.2 on 2025-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_employee_age_alter_employee_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
