# Generated by Django 5.2 on 2025-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
