# Generated by Django 5.2 on 2025-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_position_alter_employee_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='positiontitle',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='정렬 순서'),
        ),
        migrations.AddField(
            model_name='positiontitle',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='정렬 순서'),
        ),
        migrations.AddField(
            model_name='rank',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='정렬 순서'),
        ),
    ]
